name: Tests

on: ["push", "pull_request"]

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Run PHPStan
                uses: docker://jakzal/phpqa
                with:
                    args: phpstan analyze
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0', '8.1' ]
                symfony: [ '5.4.*', '6.0.*' ]
        name: Test on Symfony ${{ matrix.symfony }} with PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
            -   run: composer require symfony/framework-bundle:${{ matrix.symfony }} --no-update
            -   run: composer require symfony/form:${{ matrix.symfony }} --no-update
            -   run: composer install
            -   run: make test

    test-highest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.2' ]
                symfony: [ '6.2.*' ]
        name: Test on Symfony ${{ matrix.symfony }} with PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
            -   run: composer require symfony/framework-bundle:${{ matrix.symfony }} --no-update
            -   run: composer require symfony/form:${{ matrix.symfony }} --no-update
            -   run: composer install
            -   run: make test

    test-lowest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0' ]
                symfony: [ '5.4.*']
        name: Test lowest on Symfony ${{ matrix.symfony }} with PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
            -   run: composer require symfony/framework-bundle:${{ matrix.symfony }} --no-update
            -   run: composer require symfony/form:${{ matrix.symfony }} --no-update
            -   run: composer install
            -   run: make test-lowest

    php-cs-fixer:
        # https://github.com/jakzal/phpqa php-cs-fixer is not supported for php 8.2 (checked on 07-02-2023)
        # https://github.com/jakzal/phpqa/issues/398
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Run PHP-CS-Fixer
                #uses: docker://jakzal/phpqa
                uses: docker://jakzal/phpqa:php8.1-alpine
                with:
                    args: php-cs-fixer fix --dry-run
