name: Tests

on: [pull_request]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run PHPStan
      uses: docker://jakzal/phpqa
      with:
        args: phpstan analyze
  phpunit:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            php: ['7.2', '7.3', '7.4', '8.0']
            symfony: ['3.4.*', '4.3.*', '5.0.*', '5.2.*']
    name: Symfony ${{ matrix.symfony }} on PHP ${{ matrix.php }}  tests
    steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v1
            with:
                php-version: ${{ matrix.php }}
                coverage: none # disable xdebug, pcov
        -   run: composer require symfony/framework-bundle:${{ matrix.symfony }} --no-update
        -   run: composer require symfony/form:${{ matrix.symfony }} --no-update
        -   run: composer install
        -   run: vendor/bin/phpunit
